# Generated by Django 3.1.5 on 2021-04-01 19:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='string', max_length=25, null=True)),
                ('post', models.CharField(blank=True, default='', max_length=1440, null=True)),
                ('time_added', models.DateTimeField(default=datetime.datetime(2021, 4, 1, 19, 33, 14, 703173, tzinfo=utc), max_length=64)),
            ],
        ),
    ]
