# Generated by Django 3.1.5 on 2021-04-01 19:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.CharField(blank=True, default='string', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 19, 44, 44, 6275, tzinfo=utc), max_length=64),
        ),
    ]
