# Generated by Django 3.1.5 on 2021-04-02 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210401_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 19, 30, 45, 526274, tzinfo=utc), max_length=64),
        ),
    ]
