# Generated by Django 3.1.5 on 2021-05-09 02:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210407_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 2, 43, 7, 60567, tzinfo=utc), max_length=64),
        ),
    ]
