# Generated by Django 3.1.5 on 2021-05-09 23:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210509_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 23, 45, 35, 724901, tzinfo=utc), max_length=64),
        ),
    ]
