# Generated by Django 3.1.5 on 2021-05-26 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20210509_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 18, 28, 31, 722972, tzinfo=utc), max_length=64),
        ),
    ]
