# Generated by Django 3.1.5 on 2021-06-01 19:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20210526_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 19, 54, 58, 387774, tzinfo=utc), max_length=64),
        ),
    ]
