# Generated by Django 3.1.5 on 2021-06-07 18:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20210601_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 18, 45, 29, 892667, tzinfo=utc), max_length=64),
        ),
    ]
