# Generated by Django 3.1.5 on 2021-06-24 19:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20210621_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(blank=True, default='This user has not tweeted anything yet!', max_length=1440),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 19, 26, 58, 718439, tzinfo=utc), max_length=64),
        ),
    ]
